### ISSUE TITLE
Using tpc-ds-performance-test for RDDs

### ISSUE THREAD

**Issue by mkhoshle** [IBM/spark-tpc-ds-performance-test#22]
Hi all,

I see in the documentation that it is possible to measure the performance of Spark SQL using the TPC-DS benchmark. I wanted to ask if it is possible to use it for performance measurements in other APIs like RDDs. I am using python API with RDD abstraction and I am not sure if I can use this tool to identify performance bottlenecks.

Any thoughts?

Thanks,

**Comment by stevemart** [comment]
@bomeng please advise

**Comment by bomeng** [comment]
The idea in the pattern is to get the benchmark of Spark using TPC-DS data. For example, you can get the benchmark for certain version of Spark; while Spark codes change, the performance may be affected (improved or downgraded for certain queries). So it will help the developers to address the issues by running this from time to time. I am sure you can make the similar tool for Python using the idea here.

**Comment by mkhoshle** [comment]
Do I need to make any changes to the tool? Or there is not any change necessary to the TPC-DS. I want to use this tool to do blocked time analysis and see what are the reason for observing stragglers. But I am using PySpark and RDD abstraction, so I was wondering if it is possible to use TPC-DS for that purpose. I am not a computer science student, so I wanted to ask even if some changes are necessary to TPC-DS, to what level they would be?

**Comment by bomeng** [comment]
TPC-DS is the dataset you can use for testing (the size of the dataset can be configured), but yes, you still need to write some codes to invoke PySpark to use that dataset. Please take a look of some existing test cases written in Python for Spark, you may wanna write the similar codes.

**Comment by mkhoshle** [comment]
I think I am a little confused. So, if I want to use blocked time analysis discussed in the [paper](https://people.eecs.berkeley.edu/~keo/publications/nsdi15-final147.pdf) where can I get the source codes for doing that? Is anything available?

**Comment by bomeng** [comment]
You need to write your own codes if you decide to go with Python. As I said, you can take a look of test case codes in the Spark PySpark and write the similar codes.

**Comment by dilipbiswal** [comment]
@mkhoshle In my understanding, in this paper, they talk about instrumenting the spark source code to collect these blocked time metrics. This journey only focuses on setting up TPCDS on development environment and measure the end-to-end query times. For your work, it sounds like you need a more fine grained time-spent analysis. 

To summarize -
1) You could use TPCDS as the sample load for your analysis.
2) However, you need to instrument spark (assuming what you need is not available as existing spark metrics) in order to collect the metrics you need.

**Comment by mkhoshle** [comment]
@dilipbiswal Ok. I see now. Thank you very much for the input.

**Comment by stevemart** [comment]
Closing this as it send resolved
