### ISSUE TITLE
Generate data

### ISSUE THREAD

**Issue by hahasdnu1029** [IBM/spark-tpc-ds-performance-test#23]
Can't the generated data be placed on HDFS?
I tried to modify export TPC ds _ gendata _ dir = HDFS: / / master: 9000 / TPC ds /
. The path to HDFS is not recognized

**Comment by rhagarty** [comment]
@hahasdnu1029 - I assume you are running this from the notebook? If so, can you cut/paste the contents of the cell with error?

@dilipbiswal - any ideas?
