### ISSUE TITLE
Update ACKNOWLEDGEMENTS.md

### ISSUE THREAD

**Issue by rhagarty** [IBM/spark-tpc-ds-performance-test#4]
Typically, you would add a sentence like the following:

* Credit goes to Bo Meng and Xinyun Huang for their implementation.
* Credit goes to Huaxin Gao for her testing of this journey.

Make sure you make the names be link, pointing to their github accounts (or twitter, or linkedin).

**Comment by dilipbiswal** [comment]
@rhagarty Done.

**Comment by dilipbiswal** [comment]
@rhagarty Hi Rich, i have updated the flow contents. Could you please take a look and let me know.

**Comment by stevemart** [comment]
Closed via https://github.com/IBM/spark-tpc-ds-performance-test/commit/0ad221389f0c4f5e842dc5efe06540e987ac27e3 -- @dilipbiswal please create pull requests and add the bug submitter as a reviewer next time
