### ISSUE TITLE
Notebook creation images need to be updated

### ISSUE THREAD

**Issue by rhagarty** [IBM/spark-tpc-ds-performance-test#5]
The names, descriptions, and URL location inside the images are for the SystemML journey.

**Comment by dilipbiswal** [comment]
I will fix it @rhagarty. I was waiting for the repo to move before i made this change.

**Comment by dilipbiswal** [comment]
@rhagarty Done.

**Comment by stevemart** [comment]
Closed via https://github.com/IBM/spark-tpc-ds-performance-test/commit/ff89e04c8717640f41593ebfe54c6778a6f8d276#diff-04c6e90faac2675aa89e2176d2eec7d8 -- @dilipbiswal please create a pull request next time and add the bug submitter as a reviewer before merging.
